dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'
urlpatterns = [
    # BSU dashboard
    path('', views.index, name='index'),
    path('report/', views.report, name='report'),
    path('settings/', views.settings, name='settings'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile-edit'),
    path('profile/admin/', views.profile_admin, name='admin-edit'),
    # BSI dashboard
    path('bsi-dashboard/', views.bsi_dashboard, name='bsi-dashboard'),
    path('bsu-create/', views.bsu_create, name='bsu-create'),
    path('bsu-list/', views.bsu_list, name='bsu-list'),
    path('bsu-detail/<int:bsu_id>/', views.bsu_detail, name='bsu-detail'),
    path('bsu-detail/<int:bsu_id>/edit/', views.bsu_edit, name='bsu-edit'),
    path('bsu-detail/<int:bsu_id>/report/<str:date_str>/', views.bsu_report_detail, name='bsu-report-detail'),
    path('bsu/<int:bsu_id>/nasabah/<nasabah_id>/', views.bsu_nasabah_service),
    path('bsu/<int:bsu_id>/nasabah/', views.bsu_nasabah_service),
    # Nasabah dashboard
    path('nasabah/list/', views.nasabah_list, name="nasabah-list"),
    path('nasabah/new/', views.nasabah_form, name="nasabah-form"),
    path('nasabah/<int:nasabah_id>/profile/', views.nasabah_profile, name="nasabah-profile"),
]

form/urls.py
from django.urls import path

from form.views import interest

app_name = 'form'
urlpatterns = [
    path('interest', interest, name='interest'),
]

nasabah/urls.py
from django.urls import path
from nasabah import views

app_name = "nasabah"
urlpatterns = [
    path("<int:nasabah_id>/", views.nasabah_service),
    path("home/", views.home, name='home'),
    path("deposit/", views.deposit_list, name='deposit-list'),
    path("deposit/<str:date_str>/", views.deposit_detail, name='deposit-detail'),
    path("savings/", views.savings, name='savings'),
    path("profile/", views.profile, name='profile'),
    path("settings/", views.settings, name='settings'),
]

sirmaba/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('accounts/', include('account.urls', namespace='account')),
    path("nasabah/", include("nasabah.urls", namespace="nasabah")),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('form/', include('form.urls', namespace='form')),
    path('waste/', include('waste.urls', namespace='waste')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

waste/urls.py
from django.urls import path
from waste import views

app_name = 'waste'
urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='category-list'),
    path('categories/<int:category_id>/', views.type_list, name='type-list'),
    path('categories/<int:category_id>/edit/', views.categories_edit, name='category-edit'),
    path('type/<int:type_id>', views.type_detail, name='type-detail'),
    path('type/form/<int:category_id>/', views.type_form, name='type-form'),
]

web/urls.py
from django.urls import path
from web import views

app_name = 'web'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
]

web/templates/landing_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Sirmaba</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins|Roboto">
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.js"></script>
    <script type="text/javascript" src="{% static 'web/js/script.js' %}"></script>
  </head>
  <body id="bsi" class="background">
    <div class="overlay position-fixed d-md-none"></div>
    <!--Header Sidebar-->
    <div class="sidebar position-fixed" id="sidebar">
      <div class="sidebar-header pb-4 pl-5">
          <button class="btn btn-link float-right py-2 px-3">
            <i class="fa fa-times fa-2x"></i>
          </button>

          <div class="pt-5">
            <a class="navbar-brand" href="{% url 'web:landing_page' %}">
              <img src="{% static 'web/images/logo.png' %}" style="width: 175px; height: 90px">
            </a>
          </div>
      </div>

      <div class="sidebar-menu pt-4 pl-5" style="opacity: 0.7">
        <a href="" class="row py-2">
          <p class="font-weight-bold">Keuntungan</p>
        </a>

        <a href="#" class="row py-2">
          <p class="font-weight-bold">Cara Kerja</p>
        </a>

        <a href="#" class="row py-2">
          <p class="font-weight-bold">Jenis Sampah</p>
        </a>

        <a href="#" class="row py-2">
          <p class="font-weight-bold">Acara</p>
        </a>

        <a href="#" class="row py-2">
          <p class="font-weight-bold">Daftar Ulang</p>
        </a>

        <a href="{% url 'form:interest' %}" class="row py-2">
          <p class="font-weight-bold">Ingin Bergabung</p>
        </a>
      </div>
    </div>

    <nav class="navbar py-auto navbar-expand-lg fixed-top py-2" role="navigation">
      <button class="navbar-toggler navbar-toggler-left py-auto mr-auto" type="button">
        <i class="fa fa-bars text-white fa-2x" style="font-size: 25px"></i>
      </button>

      <div class="collapse navbar-collapse mx-3 px-5" id="navbarNav">
        <div>
          <a class="navbar-brand float-left" href="{% url 'web:landing_page' %}">
            <img src="{% static 'web/images/logo.png' %}" style="width: 175px; height: 90px">
          </a>
        </div>

        <div class="d-flex flex-row flex-end ml-auto text-white">
          <a href="#" class="row ml-3">
            <h3 class="ml-5 mr-2 my-auto">Keuntungan</h3>
          </a>

          <a href="#" class="row ml-3">
            <h3 class="ml-5 mr-1 my-auto">Cara Kerja</h3>
          </a>

          <a href="#" class="row ml-3">
            <h3 class="ml-5 mr-1 my-auto">Jenis Sampah</h3>
          </a>

          <a href="#" class="row ml-3">
            <h3 class="ml-5 mr-1 my-auto">Acara</h3>
          </a>

          <a href="#" class="row ml-3">
            <h3 class="ml-5 mr-1 my-auto">Daftar Ulang</h3>
          </a>

          <a href="{% url 'form:interest' %}" class="row ml-3">
            <h3 class="ml-5 mr-1 my-auto">Ingin Bergabung</h3>
          </a>
        </div>
      </div>
    </nav>
    <!--End Header-->

    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <form id="login-form" action="{% url 'account:login' %}" method="POST">
              {% csrf_token %}
              <div id="login_menu">
                <h2 class="text-center font-weight-bold">LOGIN KE SIRMABA</h2>
                <br>
                <button id="bsu" type="button" class="btn-common ln-green-old my-2 py-2 font-weight-bold">MASUK SEBAGAI BSU</button>
                <button id="bsi" type="button" class="btn-common ln-green-old my-2 py-2 font-weight-bold">MASUK SEBAGAI BSI</button>
                <button id="nasabah" type="button" class="btn-common ln-green-old my-2 py-2 font-weight-bold">MASUK SEBAGAI NASABAH</button>
              </div>

              <div id="login">              
                <h2 class="text-center font-weight-bold">LOGIN AKUN <span id="login_as">BSI</span></h2>
                <br>
                <div class="form-group col-md-12 px-0">
                  <h3>Username</h3>
                  <input id="username" type="text" name="username" placeholder="rafif.iqbal" class="form-control my-2" required>
                </div>

                <div class="form-group col-md-12 px-0">
                  <h3>Password</h3>
                  <input id="password" type="password" name="password" class="form-control my-2" required>
                </div>

                <button class="btn-common bg-green" type="submit"><strong>LOGIN</strong></button>
              </div>
            </form>        
          </div>
        </div>
      </div>
    </div>
    {% block content %}
    {% endblock content %}
    <script type="text/javascript">
      $('#login_menu > button').on('click', function(){
        login_as = $(this).attr('id');
        $('#login_as').html(login_as.toUpperCase());
        
        $('#login_menu').hide(300);
        $('div[id="login"]').show(300);

        if (login_as === 'bsi') {
          $('#login-form').attr('action', '{% url 'account:login' %}?next={% url 'dashboard:bsu-list' %}')

        } else if (login_as === 'bsu') {
          $('#login-form').attr('action', '{% url 'account:login' %}?next={% url 'dashboard:index' %}')
        } else if (login_as === 'nasabah') {
          $('#login-form').attr('action', '{% url 'account:login' %}?next={% url 'nasabah:home' %}')
        }
      });

      $(".modal").on("hidden.bs.modal", function(){
        $('div[id="login"]').hide();
        $('#login_menu').show();
      });
    </script>
  </body>
</html>

web/templates/landing_page.html
{% extends 'landing_base.html' %}
{% load static %}

{% block content %}
    <div id="jumbotron" class="text-center roboto text-white">
      <div>
        <br>
        <br>
        <h2 class="font-weight-bold">SISTEM INFORMASI TRANSAKSI DAN MANAJEMEN DATA</h2>
        <h2 class="font-weight-bold">BANK SAMPAH (SIRMABA) RUMAH HARUM DEPOK</h2>
        <br>
        <h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h3>
        <br>
        <br>
        <br>

        <div class="mx-auto">
          <button id="daftar_ulang" class="btn ln-white mx-2" style="width: 25%"><h3 class="font-weight-bold">DAFTAR ULANG</h3></button>
          <button type="button" id="login" class="btn bg-green mx-2" data-toggle="modal" data-target="#loginModal" style="width: 25%"><h3 class="font-weight-bold">LOGIN</h3></button>
        </div>

        <br>
        <br>
        <h3>Berminat untuk bergabung dengan kami? Isi formulir <a href="#footer" style="color: white; text-decoration: underline">disini</a></h3>
      </div>
    </div>

    <div id="keuntungan" class="roboto text-black bg-white">
      <div class="container">
        <h2 class="green-text font-weight-bold text-center">ALASAN HARUS BERGABUNG DENGAN KAMI</h2>
        <br>
        <div class="row my-3">
          <div class="col-md-6 px-4 my-3">
            <img src="https://scontent.cdninstagram.com/vp/55b8456b7e14cf3fb84a15ffa771b9d6/5D3E7D9A/t51.2885-15/e35/c0.56.450.450/23734562_2197247096967831_1163512906843684864_n.jpg?_nc_ht=scontent-sea1-1.cdninstagram.com" class="image-keuntungan my-3">
            <br>
            <strong>Keuntungan 1</strong>
            <br>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </div>
          <div class="col-md-6 px-4 my-3">
            <img src="https://scontent.cdninstagram.com/vp/55b8456b7e14cf3fb84a15ffa771b9d6/5D3E7D9A/t51.2885-15/e35/c0.56.450.450/23734562_2197247096967831_1163512906843684864_n.jpg?_nc_ht=scontent-sea1-1.cdninstagram.com" class="image-keuntungan my-3">
            <br>
            <strong>Keuntungan 2</strong>
            <br>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </div>

          <div class="col-md-6 px-4 my-3">
            <img src="https://scontent.cdninstagram.com/vp/55b8456b7e14cf3fb84a15ffa771b9d6/5D3E7D9A/t51.2885-15/e35/c0.56.450.450/23734562_2197247096967831_1163512906843684864_n.jpg?_nc_ht=scontent-sea1-1.cdninstagram.com" class="image-keuntungan my-3">
            <br>
            <strong>Keuntungan 3</strong>
            <br>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </div>
          <div class="col-md-6 px-4 my-3">
            <img src="https://scontent.cdninstagram.com/vp/55b8456b7e14cf3fb84a15ffa771b9d6/5D3E7D9A/t51.2885-15/e35/c0.56.450.450/23734562_2197247096967831_1163512906843684864_n.jpg?_nc_ht=scontent-sea1-1.cdninstagram.com" class="image-keuntungan my-3">
            <br>
            <strong>Keuntungan 4</strong>
            <br>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </div>
        </div>
        <br>
        <hr>
        <br>

        <h2 class="green-text font-weight-bold text-center">CARA KERJA BANK SAMPAH</h2>
        <br>
        <span id="">
          <img src="{% static 'web/images/cara-kerja.jpg' %}" class="w-100 h-100">
        </span>
        <br>
        <br>
        <hr>
        <br>

        <section id="sampah">
          <div class="row my-auto">
            <h2 class="green-text font-weight-bold mx-auto text-center">JENIS SAMPAH YANG DAPAT DIJUAL</h2>
          </div>
          <br>

          <div id="jenis_sampah">
            <div class="row">
              <div id="sampah_1" class="col-md-3">
                <div class="card">
                  <img class="card-img-top" src="https://i.pinimg.com/originals/81/6d/a5/816da533638aee63cfbd315ea24cccbd.jpg" alt="Card image cap">
                  <div class="card-body">
                    <strong>Kategori 1</strong>
                  </div>
                </div>
              </div>

              <div id="sampah_2" class="col-md-3">
                <div class="card">
                  <img class="card-img-top" src="https://i.pinimg.com/originals/81/6d/a5/816da533638aee63cfbd315ea24cccbd.jpg" alt="Card image cap">
                  <div class="card-body">
                    <strong>Kategori 2</strong>
                  </div>
                </div>
              </div>

              <div id="sampah_3" class="col-md-3">
                <div class="card">
                  <img class="card-img-top" src="https://i.pinimg.com/originals/81/6d/a5/816da533638aee63cfbd315ea24cccbd.jpg" alt="Card image cap">
                  <div class="card-body">
                    <strong>Kategori 3</strong>
                  </div>
                </div>
              </div>

              <div id="sampah_4" class="col-md-3">
                <div class="card">
                  <img class="card-img-top" src="https://i.pinimg.com/originals/81/6d/a5/816da533638aee63cfbd315ea24cccbd.jpg" alt="Card image cap">
                  <div class="card-body">
                    <strong>Kategori 4</strong>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <br>
          <a href="#">
            <p class="position-absolute" style="color: #888888; right: 14%">Lihat Semua(<span id="jumlah_sampah">100</span>)</p>
          </a>
          <br>
          <hr>
          <br>
          <br>
        </section>

        <section id="acara">
          <div class="row my-auto">
            <h2 class="green-text font-weight-bold mx-auto">ACARA KAMI</h2>
          </div>

          <br>
          <div id="list_acara">
            <div id="acara_1" class="card w-100 my-3">
              <div class="row">
                <div class="col-md-4">
                  <img class="card-img-top" src="https://i.pinimg.com/originals/81/6d/a5/816da533638aee63cfbd315ea24cccbd.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <h3 class="card-title font-weight-bold">Card title</h3>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                  <a href="#" style="color: #888888;">Lihat Selengkapnya</a>
                </div>
              </div>
            </div>

            <div id="acara_2" class="card w-100 my-3">
              <div class="row">
                <div class="col-md-4">
                  <img class="card-img-top" src="https://i.pinimg.com/originals/81/6d/a5/816da533638aee63cfbd315ea24cccbd.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <h3 class="card-title font-weight-bold">Card title</h3>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                  <a href="#" style="color: #888888;">Lihat Selengkapnya</a>
                </div>
              </div>
            </div>

            <div id="acara_3" class="card w-100 my-3">
              <div class="row">
                <div class="col-md-4">
                  <img class="card-img-top" src="https://i.pinimg.com/originals/81/6d/a5/816da533638aee63cfbd315ea24cccbd.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <h3 class="card-title font-weight-bold">Card title</h3>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                  <a href="#" style="color: #888888;">Lihat Selengkapnya</a>
                </div>
              </div>
            </div>

            <div id="acara_4" class="card w-100 my-3">
              <div class="row">
                <div class="col-md-4">
                  <img class="card-img-top" src="https://i.pinimg.com/originals/81/6d/a5/816da533638aee63cfbd315ea24cccbd.jpg" alt="Card image cap">
                </div>
                <div class="card-body">
                  <h3 class="card-title font-weight-bold">Card title</h3>
                  <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                  <a href="#" style="color: #888888;">Lihat Selengkapnya</a>
                </div>
              </div>
            </div>
          </div>
          <br>
          <a href="#">
              <p class="position-absolute" style="color: #888888; right: 14%">Lihat Semua(<span id="jumlah_acara">100</span>)</p>
            </a>
        </section>
        <br>

      </div>
    </div>

    <div id="footer">
      <div class="bg-green-old">
        <div class="container text-white text-center">
          Berminat untuk bergabung dengan kami
          <br>
          <br>
          <a href="{% url 'form:interest' %}">
            <button class="btn ln-green bg-white font-weight-bold">
              ISI FORM
            </button>
          </a>
        </div>
      </div>
    </div>

    <div class="modal fade" id="modal-status-success" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-body">
              <h3>Form berhasil dikirim</h3>
          </div>
        </div>
      </div>
    </div>

    <script type="text/javascript">
      var urlParams = new URLSearchParams(location.search);
      form_submit_status = urlParams.get('form_submit');

      if (form_submit_status === 'success')
        $('#modal-status-success').modal('show');
    </script>
{% endblock content %}