dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'
urlpatterns = [
    # BSU dashboard
    path('', views.index, name='index'),
    path('report/', views.report, name='report'),
    path('settings/', views.settings, name='settings'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile-edit'),
    path('profile/admin/', views.profile_admin, name='admin-edit'),
    # BSI dashboard
    path('bsi-dashboard/', views.bsi_dashboard, name='bsi-dashboard'),
    path('bsu-create/', views.bsu_create, name='bsu-create'),
    path('bsu-list/', views.bsu_list, name='bsu-list'),
    path('bsu-detail/<int:bsu_id>/', views.bsu_detail, name='bsu-detail'),
    path('bsu-detail/<int:bsu_id>/edit/', views.bsu_edit, name='bsu-edit'),
    path('bsu-detail/<int:bsu_id>/report/<str:date_str>/', views.bsu_report_detail, name='bsu-report-detail'),
    path('bsu/<int:bsu_id>/nasabah/<nasabah_id>/', views.bsu_nasabah_service),
    path('bsu/<int:bsu_id>/nasabah/', views.bsu_nasabah_service),
    # Nasabah dashboard
    path('nasabah/list/', views.nasabah_list, name="nasabah-list"),
    path('nasabah/new/', views.nasabah_form, name="nasabah-form"),
    path('nasabah/<int:nasabah_id>/profile/', views.nasabah_profile, name="nasabah-profile"),
]

nasabah/urls.py
from django.urls import path
from nasabah import views

app_name = "nasabah"
urlpatterns = [
    path("<int:nasabah_id>/", views.nasabah_service),
    path("home/", views.home, name='home'),
    path("deposit/", views.deposit_list, name='deposit-list'),
    path("deposit/<str:date_str>/", views.deposit_detail, name='deposit-detail'),
    path("savings/", views.savings, name='savings'),
    path("profile/", views.profile, name='profile'),
    path("settings/", views.settings, name='settings'),
]

sirmaba/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('accounts/', include('account.urls', namespace='account')),
    path("nasabah/", include("nasabah.urls", namespace="nasabah")),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('form/', include('form.urls', namespace='form')),
    path('waste/', include('waste.urls', namespace='waste')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transaction/urls.py
from django.urls import path
from transaction import views

app_name = 'transaction'
urlpatterns = [
    path('deposit/', views.deposit, name='deposit'),
    path('deposit/add/', views.add_deposit, name='deposit-add'),
    path('deposit/account/<int:customer_id>/', views.account_deposit, name='account-deposit'),
    path('deposit/summary/<int:tx_id>/', views.deposit_summary, name='deposit-summary'),
    path('deposit/detail/<str:date_str>/', views.deposit_detail, name='deposit-detail'),
    path('deposit-list/', views.deposit_list, name='deposit-list'),
    path('deposit-list/<str:date_str>/detail/', views.bsi_deposit_detail, name='bsi-deposit-detail'),
    path('pickup/', views.pickup, name='pickup'),
    path('pickup/call/', views.call, name='call'),
    path('pickup/history/<int:pickup_id>/', views.history, name='history'),
    path('pickup-list/', views.pickup_list, name='pickup-list'),
    path('pickup/confirm/<int:pickup_id>/', views.pickup_confirmation, name='pickup-confirm'),
]

waste/urls.py
from django.urls import path
from waste import views

app_name = 'waste'
urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='category-list'),
    path('categories/<int:category_id>/', views.type_list, name='type-list'),
    path('categories/<int:category_id>/edit/', views.categories_edit, name='category-edit'),
    path('type/<int:type_id>', views.type_detail, name='type-detail'),
    path('type/form/<int:category_id>/', views.type_form, name='type-form'),
]

web/urls.py
from django.urls import path
from web import views

app_name = 'web'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django.forms import ModelForm
from account.models import BankSampahUnit
from django.forms import TextInput, NumberInput, Textarea


class BSUCreationForm(ModelForm):
    class Meta:
        model = BankSampahUnit
        fields = ('name',)
        labels = {
            'name': 'Nama BSU',
        }


class BSUEditForm(ModelForm):
    class Meta:
        model = BankSampahUnit
        fields = (
            'name', 'est_year', 'pic', 'contact', 'address',
            'decree_no', 'decree_issuer'
        )
        labels = {
            'name': 'Nama BSU',
            'est_year': 'Tahun Berdiri',
            'pic': 'Penanggung Jawab',
            'contact': 'Nomor Telepon/HP',
            'address': 'Alamat BSU',
            'decree_no': 'No. SK',
            'decree_issuer': 'Yang mengeluarkan SK',
        }

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'est_year': NumberInput(attrs={'class': 'form-control'}),
            'pic': TextInput(attrs={'class': 'form-control'}),
            'contact': TextInput(attrs={'class': 'form-control'}),
            'address': Textarea(attrs={'class': 'form-control'}),
            'decree_no': TextInput(attrs={'class': 'form-control'}),
            'decree_issuer': TextInput(attrs={'class': 'form-control'}),
        }

dashboard/views.py
import decimal
from collections import defaultdict

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Count, Sum, F
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.utils.dateparse import parse_date
from django.utils.timezone import localdate

from account.models import BankSampahInduk, BankSampahUnit, Nasabah
from dashboard.forms import BSUCreationForm, BSUEditForm
from nasabah import views as nasabah_views
from transaction.models import TransactionDetail
from transaction.reports import WasteTransactionUnit, TransactionSummary
from waste.models import WasteType


@login_required
def index(request):
    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    waste_types = WasteType.objects.filter(category__bsi = bsu.bsi)

    return render(
        request, 
        'dashboard/bsu/index.html', 
        {
            'bsu': bsu, 
            'section': 'beranda',
            'waste_types': waste_types,
        }
    )


@login_required
def report(request):
    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    transactions = TransactionDetail.objects.filter(account=bsu).exclude(debit=None)

    total_income = 0
    total_waste = 0
    waste_debit = defaultdict(decimal.Decimal)
    timeline_income = defaultdict(decimal.Decimal)

    summary_units = []

    for tx in transactions:
        if tx.obj is None:
            total_income += tx.debit
            timeline_income[localdate(tx.timestamp).replace(day=1)] += tx.debit
        else:
            total_waste += tx.debit
            waste_debit[tx.obj] += tx.debit

            summary_units.append(WasteTransactionUnit(waste=tx.obj, data_dict={
                'amount': tx.debit,
                'unit': tx.unit,
                'price': tx.debit * tx.curr_rate,
                'currency': 'IDR',
            }))

    waste_debit.default_factory = None
    timeline_income.default_factory = None

    summary = TransactionSummary(summary_units)

    class DailyReport:
        total_weight = 0
        nasabah_set = set()
        bsu_deposit_income = 0

        customer_deposit_tax = 0
        customer_deposit_valued = 0

        customer_deposit_margin = 0
        bsu_customer_margin = 0
        net_profit = 0

    daily_report = defaultdict(DailyReport)

    for tx in transactions:
        if tx.obj is None:
            if tx.side_ref is None:
                daily_report[localdate(tx.timestamp)].customer_deposit_tax += tx.debit
            else:
                daily_report[localdate(tx.timestamp)].bsu_deposit_income += tx.debit
        else:
            daily_report[localdate(tx.timestamp)].total_weight += tx.debit

    customer_transactions = TransactionDetail.objects \
        .filter(transaction_id__in=transactions.values_list('transaction_id', flat=True)) \
        .filter(obj=None) \
        .exclude(account=bsu).exclude(debit=None)

    for tx in customer_transactions:
        daily_report[localdate(tx.timestamp)].nasabah_set.add(tx.account)
        daily_report[localdate(tx.timestamp)].customer_deposit_valued += tx.debit

    for data in daily_report.values():
        data.customer_deposit_margin = data.customer_deposit_valued - data.customer_deposit_tax
        data.bsu_customer_margin = data.bsu_deposit_income - data.customer_deposit_valued
        data.net_profit = data.bsu_customer_margin + data.customer_deposit_tax

    daily_report.default_factory = None

    return render(request, 'dashboard/bsu/report.html', {
        'section': 'laporan',
        'total_income': total_income,
        'total_waste': total_waste,
        'waste_debit': waste_debit,
        'timeline_income': sorted(timeline_income.items()),
        'summary': summary,
        'daily_report': sorted(daily_report.items(), reverse=True),
    })


@login_required
def settings(request):
    return render(request, 'dashboard/bsu/settings.html')


@login_required
def profile(request):
    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    return render(request, 'dashboard/bsu/profile.html', {'bsu': bsu})


@login_required
def profile_edit(request):
    status_code = 200

    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    if request.method == 'POST':
        profile_form = BSUEditForm(request.POST, instance=bsu)

        if profile_form.is_valid():
            bsu = profile_form.save()
        else:
            status_code = 400
    else:
        profile_form = BSUEditForm(instance=bsu)

    context = {
        'status_code': status_code,
        'profile_form': profile_form,
    }

    return render(request, 'dashboard/bsu/profile-edit.html', context, status=status_code)


@login_required
def profile_admin(request):
    status_code = 200

    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    if request.method == 'POST':
        admin_form = UserCreationForm(request.POST, instance=bsu.user)

        if admin_form.is_valid():
            admin = admin_form.save()
            update_session_auth_hash(request, admin)
        else:
            status_code = 400
    else:
        admin_form = UserCreationForm(instance=bsu.user)

    context = {
        'status_code': status_code,
        'admin_form': admin_form,
    }

    return render(request, 'dashboard/bsu/admin-edit.html', context, status=status_code)


@permission_required('account.add_banksampah')
def bsu_create(request):
    status_code = 200
    user = request.user

    if request.method == 'POST':
        bsu_admin_form = UserCreationForm(request.POST)
        bsu_data_form = BSUCreationForm(request.POST)

        if bsu_admin_form.is_valid() and bsu_data_form.is_valid():
            admin = bsu_admin_form.save()
            user_bsi = BankSampahInduk.objects.get(user=user)

            bsu = bsu_data_form.save(commit=False)
            bsu.user = admin
            bsu.bsi = user_bsi
            bsu.save()

            status_code = 201
        else:
            status_code = 400
    else:
        bsu_admin_form = UserCreationForm()
        bsu_data_form = BSUCreationForm()

    context = {
        'bsu_admin_form': bsu_admin_form,
        'bsu_data_form': bsu_data_form,
        'status_code': status_code,
        'section': 'bsu',
    }

    return render(request, 'dashboard/bsi/bsu-create.html', context)


@login_required
def bsu_list(request):
    user = request.user

    if user.is_authenticated:
        bank_sampah = BankSampahInduk.objects.get(user=user)

        if bank_sampah:
            bsu_query = BankSampahUnit.objects.filter(bsi=bank_sampah)

    return render(request, 'dashboard/bsi/bsu-list.html', {'bsu_list': bsu_query, 'section': 'bsu'})


@login_required
def bsu_detail(request, bsu_id):
    user = request.user

    bsu = BankSampahUnit.objects.filter(bsi__user=user).get(id=bsu_id)

    transactions_query = TransactionDetail.objects \
        .filter(account=bsu, obj__isnull=False, debit__isnull=False) \
        .values('timestamp__date', 'transaction_id') \
        .distinct()

    transactions_by_date_dict = {}
    for tx in transactions_query:
        date = tx.pop('timestamp__date')
        transactions_by_date_dict.setdefault(date, set()).add(tx['transaction_id'])

    transactions_by_date = {}
    for date, transactions in transactions_by_date_dict.items():
        transactions_by_date[date] = TransactionDetail.objects \
            .filter(transaction_id__in=transactions, obj=None) \
            .exclude(account=bsu) \
            .values('timestamp__date') \
            .annotate(nr_of_account=Count('account', distinct=True),
                      total_income=Sum('debit')) \
            .get()

    return render(request, 'dashboard/bsi/bsu-detail.html', {
        'section': 'bsu',
        'bsu': bsu,
        'transactions': sorted(
            transactions_by_date.values(),
            key=lambda x: x['timestamp__date'],
            reverse=True
        )
    })


@login_required
def bsu_report_detail(request, date_str, bsu_id):
    user = request.user
    bsu = BankSampahUnit.objects.filter(bsi__user=user).get(id=bsu_id)
    date = parse_date(date_str)
    print(date)

    tx_groups = TransactionDetail.objects \
        .filter(timestamp__date=date, account=bsu) \
        .exclude(obj=None).exclude(debit=None) \
        .values_list('transaction_id', flat=True) \
        .distinct()

    transactions_dicts = TransactionDetail.objects \
        .filter(transaction_id__in=tx_groups) \
        .exclude(account=bsu).exclude(obj=None).exclude(credit=None) \
        .values('account', 'obj') \
        .annotate(amount=Sum('credit'),
                  unit=F('unit'),
                  price=Sum(F('credit') * F('curr_rate')),
                  currency=F('side__unit'))

    waste_dict = {w.id: w for w in WasteType.objects
                  .filter(pk__in={tx['obj'] for tx in transactions_dicts})
                  .select_related('category')}

    transactions_units = []
    for tx in transactions_dicts:
        tx['waste'] = waste_dict[tx['obj']]

        transactions_units.append(WasteTransactionUnit(waste=tx['waste'], data_dict=tx))

    summary = TransactionSummary(transactions_units)

    return render(request, 'dashboard/bsi/bsu-report-detail.html', {
        'section': 'bsu',
        'summary': summary,
    })


@login_required
def bsu_edit(request, bsu_id):
    status_code = 200

    user = request.user
    bsu = BankSampahUnit.objects.filter(bsi__user=user).get(id=bsu_id)

    if request.method == 'POST':
        bsu_admin_form = UserCreationForm(request.POST, instance=bsu.user)
        bsu_data_form = BSUEditForm(request.POST, instance=bsu)

        admin_valid = bsu_admin_form.is_valid()
        data_valid = bsu_data_form.is_valid()

        if admin_valid or data_valid:

dashboard/templates/dashboard/bsi/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Sirmaba</title>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.css">
    {% block style %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/style-bsi.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins|Roboto">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.js"></script>
    <script type="text/javascript" src="{% static 'dashboard/js/script.js' %}"></script>
  </head>

<body id="bsi">
    <div class="wrapper">
        <div class="overlay position-fixed d-md-none"></div>
        <!-- Sidebar  -->
        <nav class="sidebar position-fixed d-md-block" id="sidebar">
            <div class="sidebar-header">
                <h3 class="main-title">SIRMABA</h3>
                <h4 class="sub-title">RUMAH HARUM</h4>
                <p class="detail">Sistem Informasi Transaksi dan Manajemen Data Bank Sampah</p>
            </div>

            <ul class="list-unstyled components">
                <p class="bsh">Bank Sampah Rumah Harum</p>
                <li id="dashboard">
                    <a href="{% url 'dashboard:bsi-dashboard' %}">Dashboard</a>
                </li>
                <li id="penjemputan">
                    <a href="{% url 'transaction:pickup-list' %}">Penjemputan Sampah</a>
                </li>
                <li id="rekapitulasi">
                    <a href="{% url 'transaction:deposit-list' %}">Rekapitulasi</a>
                </li>
                <li id="bsu">
                    <a href="{% url 'dashboard:bsu-list' %}">Bank Sampah Unit</a>
                </li>
                <li id="kategori">
                    <a href="{% url 'waste:category-list' %}">Kategori Sampah</a>
                </li>
                <li id="acara">
                    <a href="#">Acara</a>
                </li>
            </ul>
        </nav>

        <div id="content-side">
            <div id="header-button">
                <button type="button" id="sidebarCollapse" class="btn bg-green"><i class="fa fa-bars text-white fa-2x" style="font-size: 25px"></i></button>
                <div id="akun" class="ml-auto btn-group">
                    <button type="button" class="btn">{{ request.user.username }}</button>
                    <a href="{% url 'account:logout' %}?next={% url 'web:landing_page' %}"><button type="button" id="logout" class="btn"><i class="fas fa-sign-out-alt"></i></button></a>
                </div>
            </div>
            <hr>
            <br>

            {% block content %}
            {% endblock %}            
        </div>

        <script>
            var active_sidebar = $('li#{{ section }}');
            $(active_sidebar).addClass('active');
        </script>

        <div class="modal fade" id="modal-status-success" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <h3>Berhasil!</h3>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modal-status-failed" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <h3>Gagal!</h3>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            {% if status_code == 201 %}
                $('#modal-status-success').modal('show');
            {% elif status_code == 400 %}
                $('#modal-status-failed').modal('show');
            {% endif %}
        </script>
</html>

dashboard/templates/dashboard/bsi/bsu-create.html
{% extends 'dashboard/bsi/base.html' %}
{% load static %}

{% block content %}
<h2 style="color:#009867">Bank Sampah Unit</h2>
<!-- Breadcrumb Pagination -->
<ul class="breadcrumb">
<li><a href="{% url 'dashboard:bsu-list' %}">Bank Sampah Unit</a></li>
<li>Tambah BSU</li>
</ul>

<form action="{% url 'dashboard:bsu-create' %}" method="POST" class="box-bsu">
    <h2 class="form-title">TAMBAH BSU</h2>
    <div class="row">
        <div class="col-sm-6">
            <strong>Akun BSU</strong>
        </div>
    </div>
    <br>
    {% csrf_token %}
    <div class="form-group col-md-6 px-0">
        {{ bsu_data_form.name.label }}<span class="text-danger">*</span>
        <input id="name" type="text" name="name" class="form-control my-2" value="{{ bsu_data_form.name.value|default_if_none:'' }}" required>
        <small class="text-danger">{{ bsu_data_form.name.errors }}</small>
    </div>

    <div class="form-group col-md-6 px-0">
        {{ bsu_admin_form.username.label }}<span class="text-danger">*</span>
        <input id="username" type="text" name="username" class="form-control my-2" value="{{ bsu_admin_form.username.value|default_if_none:'' }}" required>
        <small class="text-danger">{{ bsu_admin_form.username.errors }}</small>
    </div>

    <div class="row">
        <div class="form-group col-md-6">
            Password Baru<span class="text-danger">*</span>
            <input id="password1" type="password" name="password1" class="form-control my-2" required>
            <small class="text-danger">{{ bsu_admin_form.password1.errors }}</small>
        </div>

        <div class="form-group col-md-6">
            Ulangi Password Baru<span class="text-danger">*</span>
            <input id="password2" type="password" name="password2" class="form-control my-2" required>
            <small class="text-danger">{{ bsu_admin_form.password2.errors }}</small>
        </div>
    </div>

    <button type="submit" value="save" class="btn-common bg-green">Simpan</button>
</form>

<div class="modal fade" id="modal-status-success" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h3>Berhasil!</h3>  
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-status-failed" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <h3>Gagal!</h3>  
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    {% if status_code == 201 %}
        $('#modal-status-success').modal('show');
        $('#modal-status-success').click(function() {
            window.setTimeout(function(){
                window.location.href = "{% url 'dashboard:bsu-list' %}";
            }, 500);
        });
        window.setTimeout(function(){
            window.location.href = "{% url 'dashboard:bsu-list' %}";
        }, 3000);
    {% elif status_code == 400 %}
        $('#modal-status-failed').modal('show');
    {% endif %}
</script>
{% endblock %}

dashboard/templates/dashboard/bsi/bsu-edit.html
{% extends 'dashboard/bsi/base.html' %}
{% load static %}

{% block content %}
<h2 style="color:#009867">Bank Sampah Unit</h2>
<!-- Breadcrumb Pagination -->
<ul class="breadcrumb">
<li><a href="{% url 'dashboard:bsu-list' %}">Bank Sampah Unit</a></li>
</ul>

<form action="{% url 'dashboard:bsu-edit' bsu_id=bsu_id %}" method="POST" class="box-bsu">
    <h2 class="form-title">UBAH BSU</h2>
    <div class="row">
        <div class="col-sm-6">
            <strong>Data BSU</strong>
        </div>
    </div>
    <br>
    {% csrf_token %}

    {% for bsu_data in bsu_data_form %}
    <div class="form-group col-md-12 px-0">
        {{ bsu_data.label }}
        {{ bsu_data }}
        {{ bsu_data.errors }}
    </div>
    {% endfor %}

    <hr>

    <div class="row">
        <div class="col-sm-6">
            <strong>Akun BSU</strong>
        </div>
    </div>
    <br>
    {% csrf_token %}

    <div class="form-group col-md-6 px-0">
        {{ bsu_admin_form.username.label }}
        <input id="username" type="text" name="username" class="form-control my-2" value="{{ bsu_admin_form.username.value }}">
        {{ bsu_admin_form.username.errors }}
    </div>

    <div class="row">
        <div class="form-group col-md-6">
            Password Baru
            <input id="password1" type="password" name="password1" class="form-control my-2">
            {{ bsu_admin_form.password1.errors }}
        </div>

        <div class="form-group col-md-6">
            Ulangi Password Baru
            <input id="password2" type="password" name="password2" class="form-control my-2">
            {{ bsu_admin_form.password2.errors }}
        </div>
    </div>

    <button type="submit" value="save" class="btn-common bg-green">Simpan</button>
</form>
{% endblock %}

dashboard/templates/dashboard/bsi/bsu-list.html
{% extends 'dashboard/bsi/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
{% endblock %}

{% block content %}
<div class="row m-0">
	<h2 style="color:#009867" class="mt-auto">Bank Sampah Unit</h2>
	<a href="{% url 'dashboard:bsu-create' %}" class="my-auto ml-auto col-md-3 px-0"><button class="py-2 px-3 btn-common ln-green-old"><i class="fa fa-plus px-1"></i><strong>TAMBAH BSU</strong></button></a>
</div>
<br>
<br>
<div class="box-bsu" style="overflow-x:auto">
	<table class="table">
		<thead>
			<th>Kode BSU</th>
			<th>Nama BSU</th>
			<th>Tahun Berdiri</th>
			<th>Penanggung Jawab</th>
			<th></th>
		</thead>
		<tbody>
			{% for bsu in bsu_list %}
			<tr>
				<td>{{ bsu.id }}</td>
				<td>{{ bsu.name }}</td>
				<td>{{ bsu.est_year }}</td>
				<td>{{ bsu.pic }}</td>
				<td class="row">
					<a href="{% url 'dashboard:bsu-detail' bsu_id=bsu.pk %}" class="col-md-6 px-1"><button class="btn btn-common ln-green-old pt-2 px-2">
						<h5>Lihat</h5>
					</button></a>
					<a href="{% url 'dashboard:bsu-edit' bsu_id=bsu.pk %}" class="col-md-6 px-1"><button class="btn btn-common bg-green pt-2 px-2">
						<h5>Ubah</h5>
					</button></a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
<script type="text/javascript">
$(document).ready( function () {
	var table = $('.table').DataTable({
		"paging": true,
		"searching": true,
		"ordering": true,
		"drawCallback": function () {
      $('.dataTables_filter').find('input[type=search]').addClass('form-control w-auto d-inline-block p-0');
      $('.dataTables_paginate').find('.current').addClass('rounded-lg ');
      $('.dataTables_wrapper').find('select').addClass('form-control w-auto d-inline-block p-0');
    }
	})
});
</script>

{% endblock %}