dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = 'dashboard'
urlpatterns = [
    # BSU dashboard
    path('', views.index, name='index'),
    path('report/', views.report, name='report'),
    path('settings/', views.settings, name='settings'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile-edit'),
    path('profile/admin/', views.profile_admin, name='admin-edit'),
    # BSI dashboard
    path('bsi-dashboard/', views.bsi_dashboard, name='bsi-dashboard'),
    path('bsu-create/', views.bsu_create, name='bsu-create'),
    path('bsu-list/', views.bsu_list, name='bsu-list'),
    path('bsu-detail/<int:bsu_id>/', views.bsu_detail, name='bsu-detail'),
    path('bsu-detail/<int:bsu_id>/edit/', views.bsu_edit, name='bsu-edit'),
    path('bsu-detail/<int:bsu_id>/report/<str:date_str>/', views.bsu_report_detail, name='bsu-report-detail'),
    path('bsu/<int:bsu_id>/nasabah/<nasabah_id>/', views.bsu_nasabah_service),
    path('bsu/<int:bsu_id>/nasabah/', views.bsu_nasabah_service),
    # Nasabah dashboard
    path('nasabah/list/', views.nasabah_list, name="nasabah-list"),
    path('nasabah/new/', views.nasabah_form, name="nasabah-form"),
    path('nasabah/<int:nasabah_id>/profile/', views.nasabah_profile, name="nasabah-profile"),
]

sirmaba/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls', namespace='web')),
    path('accounts/', include('account.urls', namespace='account')),
    path("nasabah/", include("nasabah.urls", namespace="nasabah")),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('form/', include('form.urls', namespace='form')),
    path('waste/', include('waste.urls', namespace='waste')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transaction/urls.py
from django.urls import path
from transaction import views

app_name = 'transaction'
urlpatterns = [
    path('deposit/', views.deposit, name='deposit'),
    path('deposit/add/', views.add_deposit, name='deposit-add'),
    path('deposit/account/<int:customer_id>/', views.account_deposit, name='account-deposit'),
    path('deposit/summary/<int:tx_id>/', views.deposit_summary, name='deposit-summary'),
    path('deposit/detail/<str:date_str>/', views.deposit_detail, name='deposit-detail'),
    path('deposit-list/', views.deposit_list, name='deposit-list'),
    path('deposit-list/<str:date_str>/detail/', views.bsi_deposit_detail, name='bsi-deposit-detail'),
    path('pickup/', views.pickup, name='pickup'),
    path('pickup/call/', views.call, name='call'),
    path('pickup/history/<int:pickup_id>/', views.history, name='history'),
    path('pickup-list/', views.pickup_list, name='pickup-list'),
    path('pickup/confirm/<int:pickup_id>/', views.pickup_confirmation, name='pickup-confirm'),
]

web/urls.py
from django.urls import path
from web import views

app_name = 'web'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django.forms import ModelForm
from account.models import BankSampahUnit
from django.forms import TextInput, NumberInput, Textarea


class BSUCreationForm(ModelForm):
    class Meta:
        model = BankSampahUnit
        fields = ('name',)
        labels = {
            'name': 'Nama BSU',
        }


class BSUEditForm(ModelForm):
    class Meta:
        model = BankSampahUnit
        fields = (
            'name', 'est_year', 'pic', 'contact', 'address',
            'decree_no', 'decree_issuer'
        )
        labels = {
            'name': 'Nama BSU',
            'est_year': 'Tahun Berdiri',
            'pic': 'Penanggung Jawab',
            'contact': 'Nomor Telepon/HP',
            'address': 'Alamat BSU',
            'decree_no': 'No. SK',
            'decree_issuer': 'Yang mengeluarkan SK',
        }

        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'est_year': NumberInput(attrs={'class': 'form-control'}),
            'pic': TextInput(attrs={'class': 'form-control'}),
            'contact': TextInput(attrs={'class': 'form-control'}),
            'address': Textarea(attrs={'class': 'form-control'}),
            'decree_no': TextInput(attrs={'class': 'form-control'}),
            'decree_issuer': TextInput(attrs={'class': 'form-control'}),
        }

dashboard/views.py
import decimal
from collections import defaultdict

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Count, Sum, F
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.utils.dateparse import parse_date
from django.utils.timezone import localdate

from account.models import BankSampahInduk, BankSampahUnit, Nasabah
from dashboard.forms import BSUCreationForm, BSUEditForm
from nasabah import views as nasabah_views
from transaction.models import TransactionDetail
from transaction.reports import WasteTransactionUnit, TransactionSummary
from waste.models import WasteType


@login_required
def index(request):
    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    waste_types = WasteType.objects.filter(category__bsi = bsu.bsi)

    return render(
        request, 
        'dashboard/bsu/index.html', 
        {
            'bsu': bsu, 
            'section': 'beranda',
            'waste_types': waste_types,
        }
    )


@login_required
def report(request):
    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    transactions = TransactionDetail.objects.filter(account=bsu).exclude(debit=None)

    total_income = 0
    total_waste = 0
    waste_debit = defaultdict(decimal.Decimal)
    timeline_income = defaultdict(decimal.Decimal)

    summary_units = []

    for tx in transactions:
        if tx.obj is None:
            total_income += tx.debit
            timeline_income[localdate(tx.timestamp).replace(day=1)] += tx.debit
        else:
            total_waste += tx.debit
            waste_debit[tx.obj] += tx.debit

            summary_units.append(WasteTransactionUnit(waste=tx.obj, data_dict={
                'amount': tx.debit,
                'unit': tx.unit,
                'price': tx.debit * tx.curr_rate,
                'currency': 'IDR',
            }))

    waste_debit.default_factory = None
    timeline_income.default_factory = None

    summary = TransactionSummary(summary_units)

    class DailyReport:
        total_weight = 0
        nasabah_set = set()
        bsu_deposit_income = 0

        customer_deposit_tax = 0
        customer_deposit_valued = 0

        customer_deposit_margin = 0
        bsu_customer_margin = 0
        net_profit = 0

    daily_report = defaultdict(DailyReport)

    for tx in transactions:
        if tx.obj is None:
            if tx.side_ref is None:
                daily_report[localdate(tx.timestamp)].customer_deposit_tax += tx.debit
            else:
                daily_report[localdate(tx.timestamp)].bsu_deposit_income += tx.debit
        else:
            daily_report[localdate(tx.timestamp)].total_weight += tx.debit

    customer_transactions = TransactionDetail.objects \
        .filter(transaction_id__in=transactions.values_list('transaction_id', flat=True)) \
        .filter(obj=None) \
        .exclude(account=bsu).exclude(debit=None)

    for tx in customer_transactions:
        daily_report[localdate(tx.timestamp)].nasabah_set.add(tx.account)
        daily_report[localdate(tx.timestamp)].customer_deposit_valued += tx.debit

    for data in daily_report.values():
        data.customer_deposit_margin = data.customer_deposit_valued - data.customer_deposit_tax
        data.bsu_customer_margin = data.bsu_deposit_income - data.customer_deposit_valued
        data.net_profit = data.bsu_customer_margin + data.customer_deposit_tax

    daily_report.default_factory = None

    return render(request, 'dashboard/bsu/report.html', {
        'section': 'laporan',
        'total_income': total_income,
        'total_waste': total_waste,
        'waste_debit': waste_debit,
        'timeline_income': sorted(timeline_income.items()),
        'summary': summary,
        'daily_report': sorted(daily_report.items(), reverse=True),
    })


@login_required
def settings(request):
    return render(request, 'dashboard/bsu/settings.html')


@login_required
def profile(request):
    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    return render(request, 'dashboard/bsu/profile.html', {'bsu': bsu})


@login_required
def profile_edit(request):
    status_code = 200

    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    if request.method == 'POST':
        profile_form = BSUEditForm(request.POST, instance=bsu)

        if profile_form.is_valid():
            bsu = profile_form.save()
        else:
            status_code = 400
    else:
        profile_form = BSUEditForm(instance=bsu)

    context = {
        'status_code': status_code,
        'profile_form': profile_form,
    }

    return render(request, 'dashboard/bsu/profile-edit.html', context, status=status_code)


@login_required
def profile_admin(request):
    status_code = 200

    user = request.user
    bsu = BankSampahUnit.objects.get(user=user)

    if request.method == 'POST':
        admin_form = UserCreationForm(request.POST, instance=bsu.user)

        if admin_form.is_valid():
            admin = admin_form.save()
            update_session_auth_hash(request, admin)
        else:
            status_code = 400
    else:
        admin_form = UserCreationForm(instance=bsu.user)

    context = {
        'status_code': status_code,
        'admin_form': admin_form,
    }

    return render(request, 'dashboard/bsu/admin-edit.html', context, status=status_code)


@permission_required('account.add_banksampah')
def bsu_create(request):
    status_code = 200
    user = request.user

    if request.method == 'POST':
        bsu_admin_form = UserCreationForm(request.POST)
        bsu_data_form = BSUCreationForm(request.POST)

        if bsu_admin_form.is_valid() and bsu_data_form.is_valid():
            admin = bsu_admin_form.save()
            user_bsi = BankSampahInduk.objects.get(user=user)

            bsu = bsu_data_form.save(commit=False)
            bsu.user = admin
            bsu.bsi = user_bsi
            bsu.save()

            status_code = 201
        else:
            status_code = 400
    else:
        bsu_admin_form = UserCreationForm()
        bsu_data_form = BSUCreationForm()

    context = {
        'bsu_admin_form': bsu_admin_form,
        'bsu_data_form': bsu_data_form,
        'status_code': status_code,
        'section': 'bsu',
    }

    return render(request, 'dashboard/bsi/bsu-create.html', context)


@login_required
def bsu_list(request):
    user = request.user

    if user.is_authenticated:
        bank_sampah = BankSampahInduk.objects.get(user=user)

        if bank_sampah:
            bsu_query = BankSampahUnit.objects.filter(bsi=bank_sampah)

    return render(request, 'dashboard/bsi/bsu-list.html', {'bsu_list': bsu_query, 'section': 'bsu'})


@login_required
def bsu_detail(request, bsu_id):
    user = request.user

    bsu = BankSampahUnit.objects.filter(bsi__user=user).get(id=bsu_id)

    transactions_query = TransactionDetail.objects \
        .filter(account=bsu, obj__isnull=False, debit__isnull=False) \
        .values('timestamp__date', 'transaction_id') \
        .distinct()

    transactions_by_date_dict = {}
    for tx in transactions_query:
        date = tx.pop('timestamp__date')
        transactions_by_date_dict.setdefault(date, set()).add(tx['transaction_id'])

    transactions_by_date = {}
    for date, transactions in transactions_by_date_dict.items():
        transactions_by_date[date] = TransactionDetail.objects \
            .filter(transaction_id__in=transactions, obj=None) \
            .exclude(account=bsu) \
            .values('timestamp__date') \
            .annotate(nr_of_account=Count('account', distinct=True),
                      total_income=Sum('debit')) \
            .get()

    return render(request, 'dashboard/bsi/bsu-detail.html', {
        'section': 'bsu',
        'bsu': bsu,
        'transactions': sorted(
            transactions_by_date.values(),
            key=lambda x: x['timestamp__date'],
            reverse=True
        )
    })


@login_required
def bsu_report_detail(request, date_str, bsu_id):
    user = request.user
    bsu = BankSampahUnit.objects.filter(bsi__user=user).get(id=bsu_id)
    date = parse_date(date_str)
    print(date)

    tx_groups = TransactionDetail.objects \
        .filter(timestamp__date=date, account=bsu) \
        .exclude(obj=None).exclude(debit=None) \
        .values_list('transaction_id', flat=True) \
        .distinct()

    transactions_dicts = TransactionDetail.objects \
        .filter(transaction_id__in=tx_groups) \
        .exclude(account=bsu).exclude(obj=None).exclude(credit=None) \
        .values('account', 'obj') \
        .annotate(amount=Sum('credit'),
                  unit=F('unit'),
                  price=Sum(F('credit') * F('curr_rate')),
                  currency=F('side__unit'))

    waste_dict = {w.id: w for w in WasteType.objects
                  .filter(pk__in={tx['obj'] for tx in transactions_dicts})
                  .select_related('category')}

    transactions_units = []
    for tx in transactions_dicts:
        tx['waste'] = waste_dict[tx['obj']]

        transactions_units.append(WasteTransactionUnit(waste=tx['waste'], data_dict=tx))

    summary = TransactionSummary(transactions_units)

    return render(request, 'dashboard/bsi/bsu-report-detail.html', {
        'section': 'bsu',
        'summary': summary,
    })


@login_required
def bsu_edit(request, bsu_id):
    status_code = 200

    user = request.user
    bsu = BankSampahUnit.objects.filter(bsi__user=user).get(id=bsu_id)

    if request.method == 'POST':
        bsu_admin_form = UserCreationForm(request.POST, instance=bsu.user)
        bsu_data_form = BSUEditForm(request.POST, instance=bsu)

        admin_valid = bsu_admin_form.is_valid()
        data_valid = bsu_data_form.is_valid()

        if admin_valid or data_valid:

dashboard/templates/dashboard/bsu/admin-edit.html
{% extends 'dashboard/bsu/base.html' %}
{% load static %}

{% block content %}
<div id="ubah_akun" class="abs-container">
	<span class="title">Ubah Pengaturan Akun</span>

	<div class="box">
		<form action="{% url 'dashboard:admin-edit' %}" method="POST">
			{% csrf_token %}
          	<div class="form-group col-md-6 px-0">
                        {{ admin_form.username.errors }}
          		<p>{{ admin_form.username.label }}<span class="text-danger">*</span></p>
          		<input id="username" type="text" name="username" class="form-control my-2" value={{ admin_form.username.value }} required>
          	</div>

          	<div class="form-group col-md-6 px-0">
                        {{ admin_form.password1.errors }}
          		<p>Password Baru<span class="text-danger">*</span></p>
          		<input id="password1" type="password" name="password1" class="form-control my-2" required>
          	</div>

          	<div class="form-group col-md-6 px-0">
                        {{ admin_form.password2.errors }}
          		<p>Ulangi Password Baru<span class="text-danger">*</span></p>
          		<input id="password2" type="password" name="password2" class="form-control my-2" required>
          	</div>

          	<button type="submit" value="save" class="btn-common bg-green">Simpan</button>
      </form>
	</div>
</div>
{% endblock %}

dashboard/templates/dashboard/bsu/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <title>Sirmaba</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/style-bsu.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins|Roboto">
    {% block style %}
    {% endblock %}
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.js"></script>
  </head>
  <body id="bsu">
    <nav class="navbar py-auto navbar-expand-md fixed-top shadows-bottom" role="navigation">
      <div class="d-flex d-md-none shadows-top fixed-bottom px-0 py-0 bg-white">
        <div id="menu-bar" class="row w-100 mx-auto text-center">
          <div class="col px-1 py-2">
            <a href="{% url 'dashboard:index' %}" id="beranda" class="nav-item text-black-50">
              <img src="{% static 'dashboard/icons/beranda.svg' %}" class="mb-1">
              <h5 class="my-auto font-weight-bold">Beranda</h5>
            </a>
          </div>
          <div class="col px-1 py-2">
            <a href="{% url 'transaction:deposit' %}" id="setoran" class="nav-item text-black-50">
              <img src="{% static 'dashboard/icons/setoran.svg' %}" class="mb-1">
              <h5 class="my-auto font-weight-bold">Setoran</h5>
            </a>
          </div>
          <div class="col px-1 py-1">
            <a href="{% url 'transaction:pickup' %}" id="penjemputan" class="nav-item text-black-50">
              <img src="{% static 'dashboard/icons/penjemputan.svg' %}" class="pt-0">
              <h5 class="my-auto font-weight-bold">Penjemputan</h5>
            </a>
          </div>
          <div class="col px-1 py-2">
            <a href="{% url 'dashboard:nasabah-list' %}" id="nasabah" class="nav-item text-black-50">
              <img src="{% static 'dashboard/icons/nasabah.svg' %}" class="mb-1">
              <h5 class="my-auto font-weight-bold">Nasabah</h5>
            </a>
          </div>
          <div class="col px-1 py-2">
            <a href="{% url 'dashboard:report' %}" id="laporan" class="nav-item text-black-50">
              <img src="{% static 'dashboard/icons/laporan.svg' %}" class="mb-1">
              <h5 class="my-auto font-weight-bold">Laporan</h5>
            </a>
          </div>
        </div>
      </div>

      <a href="{% url 'dashboard:index' %}" class="navbar-brand poppins green-text font-weight-bold mr-auto" href="">SIRMABA</h4></a>
      <a href="{% url 'dashboard:settings' %}"><button id="akun" class="justify-content-end ml-5">
          {{ request.user.username }}
      </button></a>

      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <div>
          <a href="{% url 'dashboard:index' %}" id="beranda" class="row mr-1 nav-item">
            <img src="{% static 'dashboard/icons/beranda.svg' %}" class="ml-5 mr-1 my-auto">
            <p class="my-auto font-weight-bold">Beranda</p>
          </a>
        </div>

        <div>
          <a href="{% url 'transaction:deposit' %}" id="setoran" class="row mr-1 nav-item">
            <img src="{% static 'dashboard/icons/setoran.svg' %}" class="ml-5 mr-1 my-auto">
            <p class="my-auto font-weight-bold">Setoran</p>
          </a>
        </div>
          
        <div>
          <a href="{% url 'transaction:pickup' %}" id="penjemputan" class="row mr-1 nav-item">
            <img src="{% static 'dashboard/icons/penjemputan.svg' %}" class="ml-5 mr-1 my-auto">
            <p class="my-auto font-weight-bold">Penjemputan</p>
          </a>
        </div>

        <div>
          <a href="{% url 'dashboard:nasabah-list' %}" id="nasabah" class="row mr-1 nav-item">
            <img src="{% static 'dashboard/icons/nasabah.svg' %}" class="ml-5 mr-1 my-auto">
            <p class="my-auto font-weight-bold">Nasabah</p>
          </a>
        </div>

        <div>
          <a href="{% url 'dashboard:report' %}" id="laporan" class="row mr-2 nav-item">
            <img src="{% static 'dashboard/icons/laporan.svg' %}" class="ml-5 mr-1 my-auto">
            <p class="my-auto font-weight-bold">Laporan</p>
          </a>
        </div>
      </div>
    </nav>

    <div id="content">
    {% block content %}

    {% endblock %}
    </div>

    <script>
        $("input[type='number']").on("keypress", function(e) {
            var blockSpecialRegex = /^[0-9]*$/;
            var key = String.fromCharCode(!e.charCode ? e.which : e.charCode);
            if (!blockSpecialRegex.test(key)) {
                e.preventDefault();
                return false;
            }
        });

        $("input[data-format='alphabet']").on("keypress", function(e) {
            var blockSpecialRegex = /^[a-zA-Z]*$/;
            var key = String.fromCharCode(!e.charCode ? e.which : e.charCode);
            if (blockSpecialRegex.test(key)) {
                e.preventDefault();
                return false;
            }
        });

    </script>

    <script>
      {% if section %}
        var active_header = $('a#{{ section }}');
        $(active_header).find('img').css('filter', 'sepia(0%) grayscale(0%)');
        $(active_header).find('img').css('opacity', '1');
      {% endif %}
    </script>
  </body>

</html>

dashboard/templates/dashboard/bsu/index.html
{% extends 'dashboard/bsu/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
		<div id="beranda" class="abs-container">
			<div class="box">
				Selamat datang,

				<a href="{% url 'dashboard:profile' %}"><span id="akun" class="green-text float-right my-auto">Lihat Data BSU</span></a>
				<p class="title green-text"><span class="green-text">{{ bsu.name }}</span></p>

				<hr>
				<div class="row mx-auto">
					<a href="{% url 'transaction:deposit' %}" class="col-md-5 mx-auto"><button id="setor_sampah" class="my-1 btn-common bg-green font-weight-bold">Setor Sampah</button></a>
					<a href="{% url 'transaction:pickup' %}" class="col-md-5 mx-auto"><button id="penjemputan" class="my-1 btn-common ln-green font-weight-bold">Jemput Sampah</button></a>
				</div>
			</div>

			<div class="box">
				<a href="{% url 'dashboard:report' %}"><span class="float-right my-auto text-secondary"><small>Lihat selengkapnya</small></span></a>
				Riwayat Pendapatan
				<br>
				<!-- nanti pilih2 lagi aja chartnya mau yang gimana -->
				<br>
				<div id="line-container"></div>
			</div>

			<div class="box">
				Daftar Harga Sampah
				<div>
					<div id='l-waste-price-searcher' class='l-search-bar'>
						<input id="cari" type="text" name="cari" class="form-control" placeholder="Cari Nama Sampah">
						<img src="{% static 'dashboard/icons/search.svg' %}"">
					</div>
					<table id='l-waste-price-table'>
						<thead>
							<th>
								<h4><strong>No.</strong></h4>
							</th>
							<th>
								<h4><strong>Nama</strong></h4>
							</th>
							<th>
								<h4><strong>Harga BSI</strong></h4>
							</th>
							<th>
								<h4><strong>Harga BSU</strong></h4>
							</th>
						</thead>
						<tbody id='l-waste-price-table__body'>
							{% for waste_type in waste_types %}
								<tr>
									<td><h5>{{ forloop.counter }}</h5></td>
									<td><h5>{{ waste_type.name }}</h5></td>
									<td><h5>Rp{{ waste_type.bsi_price|floatformat:2|intcomma }}/{{ waste_type.unit }}</h5></td>
									<td><h5>Rp{{ waste_type.bsu_price|floatformat:2|intcomma }}/{{ waste_type.unit }}</h5></td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<script src="https://cdn.anychart.com/releases/8.6.0/js/anychart-core.min.js"></script>
		<script src="https://cdn.anychart.com/releases/8.6.0/js/anychart-cartesian.min.js"></script>
		<script>
			var data = [
			  ["Jan", 10],
			  ["Feb", 45],
			  ["Mar", 35],
			  ["Apr", 55],
			  ["May", 53],
			  ["Jun", 62],
			  ["Jul", 70],
			  ["Aug", 90],
			  ["Sep", 147],
			];

			chart = anychart.line();
			var series = chart.line(data);
			chart.container("line-container");
			var labels_y = chart.yAxis().labels();
			var labels_x = chart.xAxis().labels();
			labels_y.fontSize(8);
			labels_y.rotation(90);
			labels_y.width(20);
			labels_y.padding(2);
			labels_x.fontSize(8);
			chart.draw();
		</script>
		<script type="text/javascript">
			$(document).ready(function() {
				$("#cari").on("keyup", function() {
					$('#l-waste-price-table__body > tr').each(function() {
						const $fullName = $(this).find('td:nth-child(2) > h5');
						const fullName = $fullName.text();
						const searchedValue = $('#cari').val().toLowerCase();
						const index = fullName.toLowerCase().search(searchedValue);
						if (index >= 0) {
							const prefix = fullName.substring(0, index);
							const coloredText = fullName.substring(index, index + searchedValue.length);
							const suffix = fullName.substring(index + searchedValue.length);
							$fullName.html(`
								${prefix}<span style='color:#009867;'><b>${coloredText}</b></span>${suffix}
							`);
							$(this).show();
						} else {
							$(this).hide();
						}
					});
				});
			});
		</script>
{% endblock %}

dashboard/templates/dashboard/bsu/settings.html
{% extends 'dashboard/bsu/base.html' %}
{% load static %}

{% block content %}
<div id="akun" class="abs-container d-block">
	<div id="pengaturan" class="roboto">
		<span class="title">Pengaturan Akun</span>

		<br>
		<button id="data_akun" class="col-md-6 list-group-button text-left">Lihat Data BSU</button>
		<button id="ubah_akun" class="col-md-6 list-group-button text-left">Ubah Pengaturan Akun</button>
		<button id="ubah_data" class="col-md-6 list-group-button text-left">Ubah Data Bsu</button>
		<a href="{% url 'account:logout' %}?next={% url 'web:landing_page' %}"><button class="col-md-6 list-group-button text-left">Log Out ({{ request.user.username }})</button></a>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$(document).on('click', 'button#ubah_akun', function(){
			$('html').load("{% url 'dashboard:admin-edit' %}")
		});

		$(document).on('click', 'button#ubah_data', function(){
			$('html').load("{% url 'dashboard:profile-edit' %}")
		});

		$(document).on('click', 'button#data_akun', function(){
			$('html').load("{% url 'dashboard:profile' %}")
		});

		$(document).on('click', '#beranda', function(){
			$('html').load("{% url 'dashboard:index' %}");
		})
	})
</script>
{% endblock %}